# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

inhibit_all_warnings!

target 'JabMe' do

pod 'JSQMessagesViewController'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'Reachability'

end
